[build]
  command = "cd front-end && npm run build"
  publish = "front-end/dist"

[[redirects]]
  from = "/docs/*"
  to = "/docs/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200